### ISSUE TITLE
Tracker wont work full screen, crashes in windowed view on encounter

### ISSUE THREAD

**Issue by logrovoe** [mculig/TemtemTracker#10]
hi i cannot get the tracker to work for the life of me. i have asked in forums and twitch chats and i seem to have the aspect ratio correct, c++ .net file installed, and also correct resolution. when the game is in full screen the tracker does not respond at all, when i use the game in window mode and have an encounter the tracker immediately crashes

**Comment by mculig** [comment]
These are 2 unrelated problems.

The most common issue causing people to be unable to detect the game in fullscreen is that their game's aspect ratio does not actually match the aspect ratio of their monitor (people playing in 16:9 on 16:10 monitors, for example) and this warping the image enough to misalign detection elements.

The 2nd possible issue is that you may be covering some of the detection elements. Check requirements for a list of those.

Regarding the crash on detection, this is most likely related to Issue https://github.com/mculig/TemtemTracker/issues/7
This issue is mentioned in the known issues in the update notes. Sadly, nothing I can do about it right now. I will check if fixes for this have made it into the library when updating for Cipanku.
