### ISSUE TITLE
Feature request | Captured Tems + 

### ISSUE THREAD

**Issue by MazGG** [mculig/TemtemTracker#6]
Hey Mislay! noob here ;)
I really wanna thank you for this app!
It helped me a lot with the SaiPark. and also make's me more and more want to learn code and create cool things to take part at OS projects like yours!

Anyway, I have requests for a function:
Can you add one more Table for the number of times that I captured the temtem?
-- It will help a lot and save time to go back and forth to the FreeTem to check..
--- Also with that option I could guess the amount of pen suns that I get :P

Is it possible?
and sorry if this is not the correct place.. that's my first Comment here 😁

**Comment by mculig** [comment]
There are two issues regarding this feature that make it difficult/impossible to do.

Currently there are no unique elements on the interface that display that a Temtem was released as opposed to being kept or renamed. It would be possible to detect the interface that shows up after a capture, but from there the buttons are highlighted when hovered or selected with the same colors as when they're clicked. Detecting a button hover would be possible, but I've not found anything unique to them being pressed so there is no way to know if a Temtem was kept vs released vs renamed. 

The 2nd issue is detecting levels. OCR relies on details to recognize particular letters, so errors can and do happen, and more frequently at lower resolutions as well, where less detail is present. To fix this, TemtemTracker compares the raw OCR output to known names of Temtem species using a string similarity metric called the Levenshtein distance. This works for Temtem names because the errors are usually a missed letter or two and so far names are different enough in most cases to not cause issues on a regular basis. Sometimes ambient noise still causes sufficient issues that this filtering step fails and you get completely wacky detections like a random Oree or Valiar or Zaobian out of nowhere. For numbers no such step is possible. There isn't a list of numbers that can or can not show up, so distinguishing between a false reading of 23 vs 28 isn't possible. 

Due to these two reasons, this kind of feature isn't possible. It would be highly unreliable, to a point where I feel the information present would not be sufficiently close to reality to be useful to a user compared to just knowing you've caught and released most of a particular Temtem you're hunting by just looking at the number of encounters you've had.
